// ── Korean player name dictionary ────────────────────────────
// 사전에 없는 선수는 영어 원문 그대로 표시됩니다.
export const PLAYER_KO: Record<string, string> = {
  'LeBron James': '르브론 제임스',
  'Stephen Curry': '스테판 커리',
  'Kevin Durant': '케빈 듀란트',
  'Giannis Antetokounmpo': '야니스 아데토쿤보',
  'Luka Doncic': '루카 돈치치',
  'Nikola Jokic': '니콜라 요키치',
  'Joel Embiid': '조엘 엠비드',
  'Jayson Tatum': '제이슨 테이텀',
  'Damian Lillard': '데미안 릴라드',
  'Anthony Davis': '앤서니 데이비스',
  'Kawhi Leonard': '카와이 레너드',
  'Paul George': '폴 조지',
  'Devin Booker': '데빈 부커',
  'Donovan Mitchell': '도노반 미첼',
  'Trae Young': '트레이 영',
  'Zion Williamson': '자이언 윌리엄슨',
  'Karl-Anthony Towns': '칼 앤서니 타운스',
  'Bam Adebayo': '뱀 아데바요',
  'Rudy Gobert': '루디 고베어',
  'Draymond Green': '드레이먼드 그린',
  'Klay Thompson': '클레이 탐슨',
  'James Harden': '제임스 하든',
  'Russell Westbrook': '러셀 웨스트브룩',
  'Chris Paul': '크리스 폴',
  'Jimmy Butler': '지미 버틀러',
  'Ja Morant': '자 모란트',
  'Anthony Edwards': '앤서니 에드워즈',
  'Tyrese Haliburton': '타이리스 할리버튼',
  'Paolo Banchero': '파올로 반케로',
  'Victor Wembanyama': '빅터 웸반야마',
  'Cade Cunningham': '케이드 커닝햄',
  'Evan Mobley': '에반 모블리',
  'Franz Wagner': '프란츠 바그너',
  'Jalen Brunson': '제일런 브런슨',
  'Julius Randle': '줄리어스 랜들',
  'Mikal Bridges': '미칼 브릿지스',
  'OG Anunoby': 'OG 아누노비',
  'Scottie Barnes': '스코티 반스',
  'Pascal Siakam': '파스칼 시아캄',
  'De\'Aaron Fox': '디에런 폭스',
  'Domantas Sabonis': '도만타스 사보니스',
  'Shai Gilgeous-Alexander': '셰이 길지어스-알렉산더',
  'Jamal Murray': '자말 머레이',
  'Michael Porter Jr.': '마이클 포터 주니어',
  'Jaren Jackson Jr.': '자렌 잭슨 주니어',
  'Desmond Bane': '데스먼드 베인',
  'Jaylen Brown': '제일런 브라운',
  'Al Horford': '알 호포드',
  'Derrick White': '데릭 화이트',
  'Khris Middleton': '크리스 미들턴',
  'Brook Lopez': '브룩 로페즈',
  'Jrue Holiday': '주르 할리데이',
  'Kristaps Porzingis': '크리스탑스 포르징기스',
  'Andrew Wiggins': '앤드류 위긴스',
  'Brandin Podziemski': '브랜든 포드젬스키',
  'Jordan Poole': '조던 풀',
  'Jonathan Kuminga': '조나단 쿠밍가',
  'Tyus Jones': '타이어스 존스',
  'Marcus Smart': '마커스 스마트',
  'Kyle Lowry': '카일 라우리',
  'Bobby Portis': '바비 포르티스',
  'Payton Pritchard': '페이튼 프리처드',
  'Luguentz Dort': '루겐츠 도트',
  'Nikola Vucevic': '니콜라 부체비치',
  'DeMar DeRozan': '더마 드로잔',
  'Zach LaVine': '잭 라빈',
  'Coby White': '코비 화이트',
  'Ayo Dosunmu': '아요 도순무',
  'Alperen Sengun': '알프렌 샌군',
  'Jalen Green': '제일런 그린',
  'Fred VanVleet': '프레드 밴블릿',
  'Dillon Brooks': '딜런 브룩스',
  'Aaron Gordon': '에런 고든',
  'Kentavious Caldwell-Pope': '켄타비어스 콜드웰-포프',
  'Christian Braun': '크리스천 브라운',
  'Isaiah Hartenstein': '이사야 하텐스타인',
  'Miles McBride': '마일스 맥브라이드',
  'Josh Hart': '조시 하트',
  'Donte DiVincenzo': '단테 디빈첸조',
  'Precious Achiuwa': '프레셔스 아치우와',
  'RJ Barrett': 'RJ 배럿',
  'Immanuel Quickley': '임마누엘 퀵클리',
  'Obi Toppin': '오비 토핀',
  'Tyrese Maxey': '타이리스 맥시',
  'Kelly Oubre Jr.': '켈리 오브레 주니어',
  'De\'Anthony Melton': '디앤서니 멜튼',
  'Paul Reed': '폴 리드',
  'Mo Bamba': '모 밤바',
  'Austin Reaves': '오스틴 리브스',
  'D\'Angelo Russell': '디안젤로 러셀',
  'Rui Hachimura': '하치무라 루이',
  'Gabe Vincent': '게이브 빈센트',
  'Udonis Haslem': '유도니스 해슬럼',
  'Tyler Herro': '타일러 히로',
  'Duncan Robinson': '던컨 로빈슨',
  'Caleb Martin': '케일럽 마틴',
  'Haywood Highsmith': '헤이우드 하이스미스',
  'Kevin Love': '케빈 러브',
  'Max Strus': '맥스 스트루스',
  'Darius Garland': '다리우스 갈랜드',
  'Jarrett Allen': '재럿 알랜',
  'Caris LeVert': '카리스 르버트',
  'Georges Niang': '조르주 니앙',
  'Sam Merrill': '샘 메릴',
  'Isaiah Joe': '이사야 조',
  'Saddiq Bey': '새딕 베이',
  'Bogdan Bogdanovic': '보그단 보그다노비치',
  'Clint Capela': '클린트 카펠라',
  'De\'Andre Hunter': '디안드레 헌터',
  'Larry Nance Jr.': '래리 낸스 주니어',
  'John Collins': '존 콜린스',
  'Jalen Johnson': '제일런 존슨',
  'Onyeka Okongwu': '오니에카 오콩우',
  'Damion Lee': '데미안 리',
  'Markelle Fultz': '마켈 풀츠',
  'Cole Anthony': '콜 앤서니',
  'Wendell Carter Jr.': '웬델 카터 주니어',
  'Jonathan Isaac': '조나단 아이작',
  'Gary Harris': '게리 해리스',
  'Moritz Wagner': '모리츠 바그너',
  'Jalen Suggs': '제일런 석스',
  'Anthony Black': '앤서니 블랙',
  'Goga Bitadze': '고가 비타제',
  'Richaun Holmes': '리숀 홈스',
  'Harrison Barnes': '해리슨 반스',
  'Kevin Huerter': '케빈 후에르테르',
  'Alex Len': '알렉스 렌',
  'Malik Monk': '말릭 몽크',
  'Kessler Edwards': '케슬러 에드워즈',
  'Davion Mitchell': '데이비언 미첼',
  'Keegan Murray': '키건 머레이',
  'Trey Lyles': '트레이 라일스',
  'Jabari Smith Jr.': '자바리 스미스 주니어',
  'Amen Thompson': '아멘 톰슨',
  'Cam Whitmore': '캠 윗모어',
  'Tari Eason': '타리 이슨',
  'Ben Mathurin': '벤 마틴',
  'Myles Turner': '마일스 터너',
  'Andrew Nembhard': '앤드류 넴바드',
  'Isaiah Jackson': '이사야 잭슨',
  'Bruce Brown': '브루스 브라운',
  'T.J. McConnell': 'T.J. 맥코넬',
  'Aaron Nesmith': '에런 네스미스',
  'Jordan Nwora': '조던 은워라',
  'Patrick Beverley': '패트릭 베벌리',
  'MarJon Beauchamp': '마르욘 보샹',
  'AJ Green': 'A.J. 그린',
  'Pat Connaughton': '팻 코너턴',
  'Grayson Allen': '그레이슨 앨런',
  'Taurean Prince': '토리안 프린스',
  'Norman Powell': '노먼 파월',
  'Ivica Zubac': '이비카 주박',
  'Mason Plumlee': '메이슨 플럼리',
  'Nicolas Batum': '니콜라스 바툼',
  'Bones Hyland': '본스 하일랜드',
  'James Bouknight': '제임스 부크나이트',
  'Jordan Miller': '조던 밀러',
  'Nikola Jovic': '니콜라 요비치',
  'Jaime Jaquez Jr.': '자이메 하케스 주니어',
  'Thomas Bryant': '토마스 브라이언트',
  'Isaiah Stewart': '이사야 스튜어트',
  'Killian Hayes': '킬리언 헤이즈',
  'Ausar Thompson': '오사 톰슨',
  'James Wiseman': '제임스 와이즈먼',
  'Monte Morris': '몬테 모리스',
  'Chimezie Metu': '치메지 메투',
  'Josh Giddey': '조시 기디',
  'Mike Muscala': '마이크 무스칼라',
  'Lu Dort': '루 도트',
  'Kenrich Williams': '켄리치 윌리엄스',
  'Tre Mann': '트레이 만',
  'Ousmane Dieng': '우스만 디엥',
  'Jalen Williams': '제일런 윌리엄스',
  'Aaron Wiggins': '에런 위긴스',
  'Khem Birch': '켐 버치',
  'Sterling Brown': '스털링 브라운',
  'Naz Reid': '나즈 레이드',
  'Luka Garza': '루카 가르자',
  'Mike Conley': '마이크 콘리',
  'Nickeil Alexander-Walker': '니킬 알렉산더-워커',
  'Kyle Anderson': '카일 앤더슨',
  'Leonard Miller': '레너드 밀러',
  'Jaden McDaniels': '제이든 맥다니얼스',
  'Josh Minott': '조시 미놋',
  'Troy Brown Jr.': '트로이 브라운 주니어',

  // ── 추가 선수 ──────────────────────────────────────────────
  'Chet Holmgren': '쳇 홈그렌',
  'Tre Jones': '트레이 존스',
  'Keldon Johnson': '켈든 존슨',
  'Jeremy Sochan': '제레미 소핸',
  'Devin Vassell': '데빈 바셀',
  'Malaki Branham': '말라키 브랜햄',

  'Anfernee Simons': '앤퍼니 시몬스',
  'Shaedon Sharpe': '샤에돈 샤프',
  'Scoot Henderson': '스쿳 헨더슨',
  'Toumani Camara': '투마니 카마라',

  'Brandon Ingram': '브랜든 잉그램',
  'Dejounte Murray': '디존테 머레이',
  'Jordan Hawkins': '조던 호킨스',

  'Lauri Markkanen': '라우리 마카넨',
  'Collin Sexton': '콜린 섹스턴',
  'Jordan Clarkson': '조던 클락슨',
  'Walker Kessler': '워커 케슬러',
  'Keyonte George': '케욘테 조지',
  'Taylor Hendricks': '테일러 헨드릭스',

  'Kyle Kuzma': '카일 쿠즈마',
  'Deni Avdija': '데니 아브디야',
  'Bilal Coulibaly': '빌랄 쿨리발리',
  'Corey Kispert': '코리 키스퍼트',

  'LaMelo Ball': '라멜로 볼',
  'Miles Bridges': '마일스 브릿지스',
  'Brandon Miller': '브랜든 밀러',
  'Nick Smith Jr.': '닉 스미스 주니어',
  'Grant Williams': '그랜트 윌리엄스',

  'Cason Wallace': '케이슨 월러스',

  'Gradey Dick': '그레이디 딕',
  'Ochai Agbaji': '오차이 아그바지',
  'Cam Thomas': '캠 토머스',
  'Noah Clowney': '노아 클라우니',
  'Nic Claxton': '닉 클랙스턴',

  'Ben Simmons': '벤 시몬스',
  'Day\'Ron Sharpe': '데이론 샤프',
  'Caleb Houstan': '케일럽 후스탄',

  'Patrick Williams': '패트릭 윌리엄스',
  'Alex Caruso': '알렉스 카루소',

  'Tim Hardaway Jr.': '팀 하더웨이 주니어',
  'Josh Green': '조시 그린',
  'Dereck Lively II': '데렉 라이블리 2세',
  'P.J. Washington': 'P.J. 워싱턴',

  'Dorian Finney-Smith': '도리안 피니-스미스',
  'Jarred Vanderbilt': '재럿 밴더빌트',
  'Cam Reddish': '캠 레디시',

  'Spencer Dinwiddie': '스펜서 딘위디',
  'Gary Trent Jr.': '게리 트렌트 주니어',
  'Matisse Thybulle': '매티스 티불',
  'Malik Beasley': '말리크 비즐리',
  'Dennis Schroder': '데니스 슈뢰더',
  'Reggie Jackson': '레지 잭슨',
  'Yuta Watanabe': '와타나베 유타',
  'Kelly Olynyk': '켈리 올리닉',
  'Xavier Tillman': '재비어 틸먼',
  'John Konchar': '존 콘차르',
  'Ziaire Williams': '지에르 윌리엄스',
  'Santi Aldama': '산티 알다마',
  'GG Jackson II': 'G.G. 잭슨 2세',
  'Marcus Sasser': '마커스 새서',
  'Steven Adams': '스티븐 애덤스',
  'Jeff Green': '제프 그린',
  'Kevon Looney': '케본 루니',
  'Gary Payton II': '게리 페이튼 2세',
  'Dario Saric': '다리오 사리치',
  'T.J. Warren': 'T.J. 워런',
  'Drew Eubanks': '드루 유뱅크스',
  'Nassir Little': '나시르 리틀',
  'Josh Okogie': '조시 오코기',
  'Kris Murray': '크리스 머레이',
  'Jarace Walker': '자레이스 워커',

  // ── 2024 드래프트 & 최근 주요 선수 ─────────────────────────
  'Zaccharie Risacher': '자카리 리사셰',
  'Alex Sarr': '알렉스 사르',
  'Reed Sheppard': '리드 셰퍼드',
  'Stephon Castle': '스테폰 캐슬',
  'Donovan Clingan': '도노반 클링건',
  'Rob Dillingham': '롭 딜링햄',
  'Matas Buzelis': '마타스 부젤리스',
  'Tristan da Silva': '트리스탄 다 실바',
  'Jared McCain': '재러드 맥케인',
  'Kel\'el Ware': '켈엘 웨어',
  'Devin Carter': '데빈 카터',
  'Cody Williams': '코디 윌리엄스',
  'Tidjane Salaun': '티자네 살랭',
  'Ja\'Kobe Walter': '자코비 월터',
  'Yves Missi': '이브 미시',
  'Bub Carrington': '버브 캐링턴',
  'Dalton Knecht': '달튼 크네히트',
  'Zach Edey': '잭 에디',
  'Ryan Dunn': '라이언 던',
  'Nikola Topic': '니콜라 토피치',
  'Dillon Jones': '딜런 존스',
  'Ron Holland II': '론 홀랜드 2세',
  'Terrence Shannon Jr.': '테런스 섀넌 주니어',
  'Johnny Furphy': '조니 퍼피',

  // ── 2025 드래프트 ──────────────────────────────────────────
  'Cooper Flagg': '쿠퍼 플래그',
  'Dylan Harper': '딜런 하퍼',
  'Ace Bailey': '에이스 베일리',
  'VJ Edgecombe': 'VJ 엣지컴',
  'Kon Knueppel': '콘 크누펠',
  'Kasparas Jakucionis': '카스파라스 야쿠초니스',
  'Nolan Traore': '놀란 트라오레',
  'Egor Demin': '예고르 데민',
  'Khaman Maluach': '카만 말루아크',
  'Liam McNeeley': '리엄 맥닐리',
  'Tre Johnson': '트레이 존슨',
  'Collin Murray-Boyles': '콜린 머레이-보일스',
  'Jeremiah Fears': '제레마이아 피어스',
  'Boogie Fland': '부기 플랜드',
  'Airious Bailey': '에어리어스 베일리',
  'Hugo Gonzalez': '우고 곤잘레스',
  'Asa Newell': '에이사 뉴웰',
  'Jasper Johnson': '재스퍼 존슨',
  'Tyler Betsey': '타일러 벳시',

  // ── 주요 현역 선수 추가 ────────────────────────────────────
  'CJ McCollum': 'CJ 맥컬럼',
  'Jonas Valanciunas': '요나스 발란추나스',
  'Herb Jones': '허브 존스',
  'Trey Murphy III': '트레이 머피 3세',
  'Jose Alvarado': '호세 알바라도',
  'Jalen Duren': '제일런 듀렌',
  'Jaden Ivey': '제이든 아이비',
  'Mark Williams': '마크 윌리엄스',
  'Terry Rozier': '테리 로지어',
  'Tobias Harris': '토비아스 해리스',
  'Dyson Daniels': '다이슨 대니얼스',
  'Cameron Johnson': '카메론 존슨',
  'Daniel Gafford': '대니얼 개포드',
  'Naji Marshall': '나지 마샬',
  'Derrick Jones Jr.': '데릭 존스 주니어',
  'Jerami Grant': '제라미 그랜트',
  'Peyton Watson': '페이튼 왓슨',
  'Jalen Wilson': '제일런 윌슨',
  'Buddy Hield': '버디 힐드',
};

export function getPlayerNameKo(name: string): string {
  return PLAYER_KO[name] || name;
}
